theme: jekyll-theme-minimal

title: [Lucas Liachi | Github]
description: [pagina de compartilhamento de conhecimento]

logo: [https://github.com/LucasLiachi/lucasliachi.github.io/tree/master/static/img/0.jpg]